# Generated by Django 4.2.1 on 2023-06-17 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_two', '0002_restaurant_rest_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='updated_at',
        ),
    ]
