# Generated by Django 4.2.1 on 2023-06-17 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_one', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='company_logo',
            field=models.CharField(default='nothing', max_length=45),
        ),
    ]
